### ISSUE TITLE
Custom domain and remote flag

### ISSUE THREAD

**Issue by RobGrants** [devondragon/workers-users#11]
Great example. 

It looks like some browsers require custom domain to make it work.

I tested it from London, UK and had to add --remote flag to create database:

npx wrangler d1 execute users --file=./schema.sql --remote

**Comment by devondragon** [comment]
I'm glad you got it working! Sorry for the delay I have been sick and playing catch up now.  I will update the documentation to make this more clear and ideally have better step by step instructions shortly!!

**Comment by devondragon** [comment]
Updated!  Thanks!
