### ISSUE TITLE
Let's Collaborate!

### ISSUE THREAD

**Issue by NicoPowers** [devondragon/workers-users#8]
Hi Devon!

I love the work you have done on this! I have just started using Cloudflare workers, coming from AWS land, and I have been looking to find a simple auth service from Cloudflare comparable to AWS Cognito. I was surprised to see Cloudflare has no such service, so I started to develop such a tool [here](https://github.com/NicoPowers/cf-d1-astro-lucia); I was also trying to have it serve as the foundation to build out full-stack apps using Cloudflare, but now that I am thinking about it, it should probably be a separate repo like you have here lol.

I just started working on it yesterday, but I like your implementation because you use the KV store, I am only using D1 with Lucia, so i'd like to explore your approach, and potentially see how can I help out.

Perhaps we can talk on Discord to share ideas and implementation details? I am also very new to Auth and have been trying to learn from [The Copenhagen Book](https://thecopenhagenbook.com/)

**Comment by devondragon** [comment]
Closing this issue as we've bee chatting on Discord.  Thanks a ton @NicoPowers !!!
